map:
  youmeinv:
    sentences:
      - 有美女！
      - 好看吗
      - 哟
      - 他调戏我
  nvjizhe:
    sentences:
      - 我们做的这个QQ啊
      - 用户量大
      - 消息没延时
      - 功能特别强大
      - 性能特别稳定
      - 界面特别好看
  wunian:
    sentences:
      - BUG
      - BUG
      - 吃鸡到处都是BUG！！
      - 你知道吗！
  wuleihong:
    sentences:
      - 我明天就离职
      - 我要不离职
      - 天打五雷轰
      - 卧槽
  moshou:
    sentences:
      - 你是程序员
      - 是的
      - Java还是C
      - PHP
  wangjingze:
    sentences:
      - 我从今往后不踏进公司半步
      - 辣鸡
      - 我去创业
      - 今晚去健身 @桐人
  tuboshu:
    sentences:
      - 啊？
      - 周三不加班！！！！
